-- 3.3 Queries para importação dos arquivos .csv
USE TesteNivelamento
GO

--EXEC dbo.contabil_ImportarDados @CaminhoArquivo = 'C:\Users\lucas\Downloads\Files\1T2024\1T2024.csv';



-- 1T2024 FILE

CREATE TABLE [1T2024] (
	[ID] UNIQUEIDENTIFIER PRIMARY KEY,
	[DATA] DATE NOT NULL,
	REG_ANS INT NOT NULL,
	CD_CONTA_CONTABIL INT NOT NULL,
	DESCRICAO NVARCHAR(MAX) NOT NULL,
	VL_SALDO_INICIAL DECIMAL(18, 2) NOT NULL,
	VL_SALDO_FINAL DECIMAL(18, 2) NOT NULL
);

	CREATE TABLE #TempTabela (
		Coluna1 VARCHAR(255), -- DATA
		Coluna2 VARCHAR(255), -- REG_ANS
		Coluna3 VARCHAR(255), -- CD_CONTA_CONTABIL
		Coluna4 NVARCHAR(MAX), -- DESCRICAO
		Coluna5 VARCHAR(255), -- VL_SALDO_INICIAL
		Coluna6 VARCHAR(255)  -- VL_SALDO_FINAL
	);

	BULK INSERT #TempTabela
	FROM 'C:\Users\lucas\Downloads\Files\1T2024\1T2024.csv'
	WITH (
		FORMAT = 'CSV',
		FIELDTERMINATOR = ';',
		ROWTERMINATOR = '\n',
		FIRSTROW = 2, -- Ignora cabeçalho
		CODEPAGE = '65001' -- Para suporte UTF-8
	);

	INSERT INTO [1T2024] (
		[ID],
		[DATA], 
		REG_ANS, 
		CD_CONTA_CONTABIL, 
		DESCRICAO, 
		VL_SALDO_INICIAL, 
		VL_SALDO_FINAL
	)
	SELECT 
		NEWID(),
		TRY_CONVERT(DATE, Coluna1),
		TRY_CONVERT(INT, Coluna2),
		TRY_CONVERT(INT, Coluna3),
		Coluna4,
		TRY_CONVERT(DECIMAL(18,2), REPLACE(Coluna5, ',', '.')),
		TRY_CONVERT(DECIMAL(18,2), REPLACE(Coluna6, ',', '.'))
	FROM #TempTabela;
	DROP TABLE #TempTabela;
GO


-- 2T2024 FILE

CREATE TABLE [2T2024] (
	[ID] UNIQUEIDENTIFIER PRIMARY KEY,
	[DATA] DATE NOT NULL,
	REG_ANS INT NOT NULL,
	CD_CONTA_CONTABIL INT NOT NULL,
	DESCRICAO NVARCHAR(MAX) NOT NULL,
	VL_SALDO_INICIAL DECIMAL(18, 2) NOT NULL,
	VL_SALDO_FINAL DECIMAL(18, 2) NOT NULL
);
	CREATE TABLE #TempTabela2 (
		Coluna1 VARCHAR(255), -- DATA
		Coluna2 VARCHAR(255), -- REG_ANS
		Coluna3 VARCHAR(255), -- CD_CONTA_CONTABIL
		Coluna4 NVARCHAR(MAX), -- DESCRICAO
		Coluna5 VARCHAR(255), -- VL_SALDO_INICIAL
		Coluna6 VARCHAR(255)  -- VL_SALDO_FINAL
	);

	BULK INSERT #TempTabela2
	FROM  'C:\Users\lucas\Downloads\Files\2T2024\2T2024.csv'
	WITH (
		FORMAT = 'CSV',
		FIELDTERMINATOR = ';', 
		ROWTERMINATOR = '\n', 
		FIRSTROW = 2, -- Ignora cabeçalho
		CODEPAGE = '65001' -- Para suporte UTF-8
	);

	INSERT INTO [2T2024] (
		[ID],
		[DATA], 
		REG_ANS, 
		CD_CONTA_CONTABIL, 
		DESCRICAO, 
		VL_SALDO_INICIAL, 
		VL_SALDO_FINAL
	)
	SELECT 
		NEWID(),
		TRY_CONVERT(DATE, Coluna1),
		TRY_CONVERT(INT, Coluna2),
		TRY_CONVERT(INT, Coluna3),
		Coluna4,
		TRY_CONVERT(DECIMAL(18,2), REPLACE(Coluna5, ',', '.')),
		TRY_CONVERT(DECIMAL(18,2), REPLACE(Coluna6, ',', '.'))
	FROM #TempTabela2;
	DROP TABLE #TempTabela2;
GO


-- 3T2024 FILE
CREATE TABLE [3T2024] (
	[ID] UNIQUEIDENTIFIER PRIMARY KEY,
	[DATA] DATE NOT NULL,
	REG_ANS INT NOT NULL,
	CD_CONTA_CONTABIL INT NOT NULL,
	DESCRICAO VARCHAR(MAX) NOT NULL,
	VL_SALDO_INICIAL DECIMAL(18, 2) NOT NULL,
	VL_SALDO_FINAL DECIMAL(18, 2) NOT NULL
);

	CREATE TABLE #TempTabela3 (
		Coluna1 VARCHAR(255), -- DATA
		Coluna2 VARCHAR(255), -- REG_ANS
		Coluna3 VARCHAR(255), -- CD_CONTA_CONTABIL
		Coluna4 NVARCHAR(MAX), -- DESCRICAO
		Coluna5 VARCHAR(255), -- VL_SALDO_INICIAL
		Coluna6 VARCHAR(255)  -- VL_SALDO_FINAL
	);

	BULK INSERT #TempTabela3
	FROM  'C:\Users\lucas\Downloads\Files\3T2024\3T2024.csv'
	WITH (
		FORMAT = 'CSV',
		FIELDTERMINATOR = ';', 
		ROWTERMINATOR = '\n', 
		FIRSTROW = 2, -- Ignora cabeçalho
		CODEPAGE = '65001' -- Para suporte UTF-8
	);

	INSERT INTO [3T2024] (
			[ID],
			[DATA], 
			REG_ANS, 
			CD_CONTA_CONTABIL, 
			DESCRICAO, 
			VL_SALDO_INICIAL, 
			VL_SALDO_FINAL
		)
	SELECT 
		NEWID(),
		TRY_CONVERT(DATE, Coluna1),
		TRY_CONVERT(INT, Coluna2),
		TRY_CONVERT(INT, Coluna3),
		Coluna4,
		TRY_CONVERT(DECIMAL(18,2), REPLACE(Coluna5, ',', '.')),
		TRY_CONVERT(DECIMAL(18,2), REPLACE(Coluna6, ',', '.'))
	FROM #TempTabela3;
	DROP TABLE #TempTabela3;
GO


-- 4T2024 FILE
CREATE TABLE [4T2024] (
	[ID] UNIQUEIDENTIFIER PRIMARY KEY,
	[DATA] DATE NOT NULL,
	REG_ANS INT NOT NULL,
	CD_CONTA_CONTABIL INT NOT NULL,
	DESCRICAO VARCHAR(MAX) NOT NULL,
	VL_SALDO_INICIAL DECIMAL(18, 2) NOT NULL,
	VL_SALDO_FINAL DECIMAL(18, 2) NOT NULL
);

	CREATE TABLE #TempTabela4 (
		Coluna1 VARCHAR(255), -- DATA
		Coluna2 VARCHAR(255), -- REG_ANS
		Coluna3 VARCHAR(255), -- CD_CONTA_CONTABIL
		Coluna4 NVARCHAR(MAX), -- DESCRICAO
		Coluna5 VARCHAR(255), -- VL_SALDO_INICIAL
		Coluna6 VARCHAR(255)  -- VL_SALDO_FINAL
	);

	BULK INSERT #TempTabela4
	FROM  'C:\Users\lucas\Downloads\Files\4T2024\4T2024.csv'
	WITH (
		FORMAT = 'CSV',
		FIELDTERMINATOR = ';', 
		ROWTERMINATOR = '\n', 
		FIRSTROW = 2, -- Ignora cabeçalho
		CODEPAGE = '65001' -- Para suporte UTF-8
	);

	INSERT INTO [4T2024] (
		[ID],
		[DATA], 
		REG_ANS, 
		CD_CONTA_CONTABIL, 
		DESCRICAO, 
		VL_SALDO_INICIAL, 
		VL_SALDO_FINAL
	)
	SELECT 
		NEWID(),
		TRY_CONVERT(DATE, Coluna1),
		TRY_CONVERT(INT, Coluna2),
		TRY_CONVERT(INT, Coluna3),
		Coluna4,
		TRY_CONVERT(DECIMAL(18,2), REPLACE(Coluna5, ',', '.')),
		TRY_CONVERT(DECIMAL(18,2), REPLACE(Coluna6, ',', '.'))
	FROM #TempTabela4;
	DROP TABLE #TempTabela4;
GO